CREATE TABLE user (
  userId INT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NULL,
  password TEXT NULL,
  name VARCHAR(255) NULL,
  surname VARCHAR(255) NULL,
  mobile VARCHAR(16) NULL,
  role ENUM('USER', 'ADMIN') NULL DEFAULT 'USER',
  PRIMARY KEY (userId)
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE blog (
  blogId INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NULL,
  author VARCHAR(255),
  date VARCHAR(10),
  views INT UNSIGNED NULL,
  userId INT UNSIGNED NOT NULL,
  PRIMARY KEY (blogId),
  FOREIGN KEY (userId) REFERENCES user(userId)
);

CREATE TABLE image (
  imageId INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  src TEXT NULL,
  is_main TINYINT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE blog_image (
	blogId INT UNSIGNED NOT NULL,
  imageId INT UNSIGNED NOT NULL PRIMARY KEY,
  FOREIGN KEY (blogId) REFERENCES blog(blogId),
  FOREIGN KEY (imageId) REFERENCES image(imageId)
);